Feature/register
Caro-L-dev/lingi-club pull request #10
Opened 2024-05-25 19:44 UTC by atou555

2024-05-25 20:52 UTC, arnaudpant requested changes
Je t'ai noté quelques axes d'amelioration avec principalement react-hook-form qui est deja intégré aux composants de shadCN et beaucoup mieux pour gerer des formulaires.

Tu as pushé ta branche mais tant que celle-ci n'est pas fonctionnelle avec la connexion a Firebase ca ne sert a rien ! On push sa branche pour faire un code review avec comme finalité un merge sur develop, et donc que ca fonctionne en production. 

Le hook de Caroline va bientôt être en ligne normalement, il est en code review. Une fois disponible connecte tes formulaires a Firebase avec son code obtenu pqr un pull et ensuite tu pourras faire un PR sur ta branche.

2024-05-25 20:52 UTC, arnaudpant commented on globals.css
> +    --input: 224 11% 95%;
Pourquoi changer cette valeur ?

2024-05-25 20:52 UTC, arnaudpant commented on src/Register.tsx
> +  return (
Tu utilises les composants de shadCN mais pas react-hook-form qui est integré normalement.

2024-05-25 20:52 UTC, arnaudpant commented on src/components/Wrapper.tsx
Pourquoi supprimer Wrapper ?

2024-05-25 20:52 UTC, arnaudpant commented on src/main.tsx
> +const rootElement = document.getElementById("root");
Je prefere comme ca perso:
`ReactDOM.createRoot(document.getElementById("root")!).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);`

2024-05-25 20:52 UTC, arnaudpant commented on src/pages/Register.tsx
> -      alert("Veuillez sélectionner un rôle avant de vous inscrire");
Avec react-hook-form pas besoin de gerer ce genre de chose

2024-05-26 15:21 UTC, atou555 commented on src/components/Wrapper.tsx
il y en avait en doublon

2024-05-26 15:23 UTC, atou555 commented on src/Register.tsx
> +  return (
Oui je viens d'appliquer ton conseil c'est vrai qu'il y a moins de code, plus épuré

2024-05-26 15:27 UTC, atou555 commented on globals.css
> +    --input: 224 11% 95%;
Car les barres input on ne les voyaient pas bien. C'est pour ça. Je ne sais pas si c'est conventionnelle de faire ça par contre.

2024-05-26 15:38 UTC, atou555 commented on src/main.tsx
> +const rootElement = document.getElementById("root");
Comme tu veux, mais lorsque je l'implémente en local document.getElementById est affiché comme une erreur donc en voulant le résoudre ça m'a finalement conduit au résultat affiché. Alors du coup même si il dit qu'il ya une erreur alors que c'est une fonction javascript on la conserve. peut être en mettant windows.document.getElementById ça règlerait le souçi

2024-05-26 15:39 UTC, atou555 commented on src/pages/Register.tsx
> -      alert("Veuillez sélectionner un rôle avant de vous inscrire");
ok je vois, je note.

2024-05-27 05:10 UTC, arnaudpant commented on src/main.tsx
> +const rootElement = document.getElementById("root");
Je crois que c'est un doublon le bon fichier App.jsx est dans src. 
Je regarde ça ce soir

2024-05-27 20:15 UTC, atou555 commented on src/main.tsx
> +const rootElement = document.getElementById("root");
Ok c'est bon

2024-05-28 02:49 UTC, closed without merging