feat: firebase and firebase auth initialization + creation of logIn and register hooks and types
Caro-L-dev/lingi-club pull request #12
Opened 2024-05-27 18:09 UTC by Aurelia77

Nouveau PR suite aux modifications du précédent selon les commentaires d'Arnaud (amélioration des hooks useLogIn et useRegister)

2024-05-27 20:50 UTC, arnaudpant requested changes
Encore un peu de taf 😥

2024-05-27 20:50 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +import { useState } from 'react';
useAuth.ts.ts ???

2024-05-27 20:50 UTC, arnaudpant commented on src/types/Forms.ts
> +export interface RegisterFormType {
Utiliser les types plutot que les interfaces

2024-05-27 20:50 UTC, arnaudpant commented on src/types/Forms.ts
> +}
Tu te repetes ! DRY
```
export type FormType = {
    email: string;
    password: string;
};

export type RegisterFormType = FormType;
export type LogInFormType = FormType

// Ce qui permet si plus tard tu veux ajouter une props uniquement dans LogInFormType par exemple:
export type LogInFormType = FormType & {
    id: string;
};

2024-05-27 20:50 UTC, arnaudpant commented on src/App.tsx
> +        <ToastContainer />
Plutot dans main.tsx

2024-05-27 20:50 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +}
Alors, le principal pb vient du fait que le user ne reste pas connecté. 
J'arrive a me connecter avec les faux comptes, j'ai bien le retour sur la page d'accueil avec le toast qui s'affiche. En faisant des erreurs voulues j'ai le bon comportement etc...
Mais une fois connecté j'ai le navigate("/") qui me renvoi bien a la page Accueil sauf que si je log le state que j'ai créé pour voir si on est connecté ou pas (`userConnected`) il repasse a false. Je pensais que c'était en recliquant sur Connexion qui faisait repasser userConnected sur false mais non !
Si tu log userConnected sur la page Accueil tu vois qu'il se connecte et déconnecte de suite ...
Et meme en mettant userCredential.user dans userConnected plutot qu'un boolean ca fait la meme chose

Je regarderai demain plus en detail

2024-05-27 20:50 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +  const [error, setError] = useState<string | null>(null);
Merci de rajouter ce state pour eviter des try catch coté front
` const [userConnected, setUserConnected] = useState<boolean>(false);`

2024-05-27 20:50 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +      toast.success(`Connexion réussie (${userCredential.user.email})`);
` setUserConnected(true)`

2024-05-27 20:50 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +  return { register, logIn, loading, error };
`return { register, logIn, loading, error, userConnected };`

2024-05-28 17:15 UTC, arnaudpant commented on src/hooks/useAuth.ts.ts
> +}
Je pense que ca vient du fait que ton hook fait la connexion et l'inscription mais pas la recuperation de compte sur Firebase via la base de données listant les utilisateurs

2024-05-29 14:14 UTC, Aurelia77 commented on src/types/Forms.ts
> +}
Ok

2024-05-29 14:26 UTC, Aurelia77 commented on src/hooks/useAuth.ts.ts
> +  const [error, setError] = useState<string | null>(null);
Ok c'est fait.

2024-05-29 14:42 UTC, Aurelia77 commented on src/hooks/useAuth.ts.ts
> +}
J'ai ajouté onAuthStateChanged dans useAuth ce qui fait que l'utilisateur reste connecté lors du rechargement de la page.

2024-05-29 20:40 UTC, arnaudpant reviewed
De mon point de vue le PR est validé sauf que j'ai pas testé la partie inscription sans parler de mon bug avec le toast.
J'attends donc que Coralie valide le PR de Madi quand elle aura validé la partie Inscription.
Ensuite je validerai ton PR

2024-05-29 20:40 UTC, arnaudpant commented on src/hooks/useAuth.ts
> +      toast.success(`Inscription réussie (${userCredential.user.email})`);
Ajouter un délai de 2s sinon c'est pénible:
```
toast.success(`Inscription réussie (${userCredential.user.email})`, {
        autoClose: 2000,
      });
```

2024-05-29 20:40 UTC, arnaudpant commented on src/hooks/useAuth.ts
> +      toast.success(`Connexion réussie (${userCredential.user.email})`);
Idem pour le délai de fermeture du toast

2024-05-29 20:40 UTC, arnaudpant commented on src/hooks/useAuth.ts
> +        data: userCredential.user
Pour se connecter pas besoin de return data. Tu peux effacer

2024-05-29 22:48 UTC, Aurelia77 commented on src/hooks/useAuth.ts
> +      toast.success(`Inscription réussie (${userCredential.user.email})`);
J'ai ajouté autoClose={2000} dans main

2024-05-29 22:48 UTC, Aurelia77 commented on src/hooks/useAuth.ts
> +      toast.success(`Connexion réussie (${userCredential.user.email})`);
ok !

2024-05-29 22:51 UTC, Aurelia77 commented on src/hooks/useAuth.ts
> +        data: userCredential.user
Oui c'est vrai, fait !

2024-05-30 20:59 UTC, arnaudpant reviewed
Ok pour la partie connexion 👍🏻

2024-06-03 19:17 UTC, arnaudpant approved these changes
OK

2024-06-03 19:18 UTC, merged