chore: hide button according to state navbar
Caro-L-dev/lingi-club pull request #14
Opened 2024-05-29 12:45 UTC by Caro-L-dev

2024-05-29 19:47 UTC, arnaudpant requested changes

2024-05-29 19:47 UTC, arnaudpant commented on src/components/navbar/Navbar.tsx
>  const Navbar: React.FC = () => {
J'ai fait une petite formation la semaine dernière où on nous a dit que dans les TypeScript moderne on ne typait plus les Component.
C'est pour info

2024-05-29 19:47 UTC, arnaudpant commented on src/components/navbar/Navbar.tsx
> +  const [isConnected] = useState(true);
Ta logique est bonne mais comme pour Madi: C'est pas fonctionnelle avec le back donc pas de validation de PR et pas de push sur develop 🥺
Il va falloir que tu attendes le hook d'Aurelia pour implementer la fonctionnalité de déconnexion + l'affichage conditionnel des buttons

2024-05-30 10:49 UTC, Caro-L-dev commented on src/components/navbar/Navbar.tsx
>  const Navbar: React.FC = () => {
Oh ok. 
Quelle formation ?

2024-05-30 10:49 UTC, Caro-L-dev commented on src/components/navbar/Navbar.tsx
> +  const [isConnected] = useState(true);
Bien reçu

2024-05-30 21:05 UTC, arnaudpant commented on src/components/navbar/Navbar.tsx
>  const Navbar: React.FC = () => {
Une formation payante en vidéo, en anglais

2024-05-31 19:46 UTC, arnaudpant requested changes

2024-05-31 19:46 UTC, arnaudpant commented on src/components/navbar/Navbar.tsx
> +            <Link to="/">Déconnexion</Link>
Je valide parce qu'Aurelia n'a pas encore codé la fonction de déconnexion.
Je le rajoute dans le sprint 2 pour elle

2024-05-31 19:46 UTC, arnaudpant commented on src/components/navbar/Navbar.tsx
> +              <Link to="/login">Connexion</Link>
La route pour la page de Connexion c'est:
`<Link to="/connexion">Connexion</Link>`
Attention de changer dans App.tsx egalement

2024-06-01 16:36 UTC, arnaudpant approved these changes

2024-06-01 16:37 UTC, merged