Feature/user data management/aurelia
Caro-L-dev/lingi-club pull request #33
Opened 2024-06-20 13:43 UTC by Aurelia77

2024-06-21 19:00 UTC, arnaudpant requested changes
2 modifs

2024-06-21 19:00 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +    console.log(data)
Pas de console.log en prod

2024-06-21 19:00 UTC, arnaudpant commented on src/types/User.ts
> +    region: string | null;
region: RegionType
// Ajouter un type RegionType :  "Auvergne-Rhône-Alpes" | "Bourgogne-Franche-Comté" | "Bretagne" | "Centre-Val de Loire" | "Corse" | "Grand Est" | "Hauts-de-France" | "Île-de-France" | "Normandie" | "Nouvelle-Aquitaine" | "Occitanie" | "Pays de la Loire" | "Provence-Alpes-Côte d'Azur" | null

2024-06-25 13:28 UTC, Aurelia77 commented on src/pages/registration/Registration.tsx
> +    console.log(data)
oui je l'ai oublié :)

2024-06-25 13:28 UTC, Aurelia77 commented on src/types/User.ts
> +    region: string | null;
ok je l'ajoute

2024-06-25 13:30 UTC, Aurelia77 commented on src/types/User.ts
> +    region: string | null;
merci !

2024-06-25 16:38 UTC, arnaudpant approved these changes

2024-06-25 16:38 UTC, merged