feature calendar update
Caro-L-dev/lingi-club pull request #39
Opened 2024-07-04 09:41 UTC by atou555

2024-07-06 12:03 UTC, arnaudpant requested changes
Premiere etape pour alleger la correction

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +  const [role, setRole] = useState<string>("");
Faire un type avec les options prédifines
```
const [role, setRole] = useState<"family" | "apprenant" | null>(null);
```

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +type RoleSelectionProps = {
Les types doivent etre dans un fichier .ts dans le dossier types

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +      <Card>
Non responsive !
Revoir le css

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +const RoleSelection = ({ setRole }: RoleSelectionProps) => {
RoleSelection doit etre dans un autre fichier

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +  return (
C'est juste une option a choisir entre 2 possibilités, pour moi pas besoin de faire un composant en plus.
On peut faire plus simple directement dans le composant Form de Registration

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
> +            <Button
Copier coller mon bouton Connexion avec un spinner integré.
Voir video de Mike ou il dit qu'il faut un spinner

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/Registration.tsx
>      if (!role) {
Dans le submit on doit avoir l'envoi vers la page pour remplir le formulaire suivant en fonction du role choisi

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/RegistrationFamily.tsx
> +
Il faut renvoyer sur la page d'accueil apres le toast.succes

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/RegistrationStudent.tsx
> +              type="submit"
Idem pour le spinner depuis mon button Connexion

2024-07-06 12:03 UTC, arnaudpant commented on src/pages/registration/RegistrationStudent.tsx
> +    console.log("Données du formulaire : ", data);
Pas de console.log
Renvoyer vers la page d'accueil

2024-07-23 11:29 UTC, atou555 commented on src/pages/registration/Registration.tsx
> +  return (
J'ai pas compris la requête.

2024-08-10 13:11 UTC, closed without merging