feature: adding family info page
Caro-L-dev/lingi-club pull request #43
Opened 2024-07-09 18:25 UTC by Aurelia77

2024-07-09 19:55 UTC, arnaudpant requested changes

2024-07-09 19:55 UTC, arnaudpant commented on src/hooks/useAuth.ts
> +  familyLangage: null,
attention avec ces changements tu vas peter le code des autres

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +const Familly: React.FC = () => {
Details mais on ne met plus react.FC en typeScript moderne

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +                    // setData(response as FamilyData);
com a supprimer

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +                    console.log(response);
console.log a supprimer

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +        return <p>Chargement...</p>;
Faudrait faire un vrai composant Spinner pour les pages, qui s'affiche en milieu et centré etc. plutot qu'un <p>
Surtout que je l'ai vu dans d'autres pages le chargement

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +    console.log(email)
log a supprimer

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +                            <ItemInfo region={region || undefined} icon={<MapPin />} />
pas de undefined, null ou "" selon ce que tu as dans le type

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +                        <Button className="w-full lg:w-fit">Réserver</Button>
ajouter le spinner de mon formulaire de Connexion et renvoyer sur la page d'accueil en attendant

2024-07-09 19:55 UTC, arnaudpant commented on src/pages/familly/Familly.tsx
> +            <CardHeader className="relative w-full lg:w-1/2">
Si tu as repris les card de la page d'accueil je les ai modifié dans ma branche donc faudra les modifier dans ton code

2024-07-10 06:32 UTC, Aurelia77 commented on src/hooks/useAuth.ts
> +  familyLangage: null,
J'ai mis un commentaire hier justement en disant que ça allait peut être vous poser des problèmes, et j'ai pas eu de retour donc j'ai corrigé. Mais ok je remets comme avant et on fera les corrections de partout à la fin.

2024-07-10 06:33 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +                    // setData(response as FamilyData);
Désolée pour les console.log et les commentaires j'ai pas vérifié !!!

2024-07-10 06:33 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +const Familly: React.FC = () => {
Ah oui, j'ai pris ça avec copilote... Merci !

2024-07-10 06:34 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +        return <p>Chargement...</p>;
Ok m'en occupe !

2024-07-10 06:34 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +                        <Button className="w-full lg:w-fit">Réserver</Button>
ok !

2024-07-10 06:38 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +            <CardHeader className="relative w-full lg:w-1/2">
ok je vais voir ça.

2024-07-10 07:55 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +                        <Button className="w-full lg:w-fit">Réserver</Button>
ok je renvoie sur la page d'accueil mais je ne vois pas pourquoi mettre un spinner ici car il n'y a pas d'attente..?

2024-07-10 08:00 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +                            <ItemInfo region={region || undefined} icon={<MapPin />} />
ok j'ai mis "" sauf pour le prix là j'ai laissé undefined car c'est un number.

2024-07-10 08:09 UTC, Aurelia77 commented on src/pages/familly/Familly.tsx
> +            <CardHeader className="relative w-full lg:w-1/2">
C'est bon j'ai repris le même CSS. On verra plus tard si on affiche différemment une seule famille, le plus important pour l'instant c'est que ça marche !

2024-07-10 14:52 UTC, merged