feat: details family page
Caro-L-dev/lingi-club pull request #56
Opened 2024-07-31 15:12 UTC by Caro-L-dev

Les datas dynamique ne fonctionnent pas.
Remplacer calendrier et dates par les bon éléments.

2024-08-01 09:47 UTC, arnaudpant requested changes

2024-08-01 09:47 UTC, arnaudpant commented on src/App.tsx
> +          <Route path="/user-infos" element={<UserInfos />} />
Ton fichier ne doit pas etre a jour puisqu'il manque les routes vers stripe

2024-08-01 09:47 UTC, arnaudpant commented on src/components/hostFamilyCard/HostFamilyCard.tsx
> +                onClick={() => navigate("/family-details/:id")}
Attention quand on clique sur la card sauf sur le bouton reserver on renvoi sur `<Link to={`/family-details/${hostFamily.uid}`} state={hostFamily}>` [Voir ligne 26]
Quand on clique sur reserver on renvoi sur stripe ! ou alors il faut changer `Reserver` par `plus d'infos` par exemple.
En plus ton ` onClick={() => navigate("/family-details/:id")}` pas sur qu'il fonctionne correctement puisque le id est en dur

2024-08-01 09:47 UTC, arnaudpant commented on src/pages/family/Family.tsx
> +              className="w-full lg:w-fit"
La aussi, faudra attendre le PR d'Aurelia qui est en cours de validation. Trop de differences donc attend et pull develop sur ta branche pour mettre a jour

2024-08-01 09:47 UTC, arnaudpant commented on src/pages/family/FamilyDetails.tsx
> +              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco l
Pas fan du lorem puisque normalement toutes les descriptions sont remplies ...

2024-08-01 09:47 UTC, arnaudpant commented on src/pages/search/SearchFamily.tsx
> +      <TypographyP className="flex flex-col py-4 text-center">
J'avais viré typography de ma barre de recherche a cause de bug et tu l'as remis ...

2024-08-01 09:54 UTC, Caro-L-dev commented on src/pages/search/SearchFamily.tsx
> +      <TypographyP className="flex flex-col py-4 text-center">
Je ne savais pas

2024-08-01 09:54 UTC, Caro-L-dev commented on src/pages/family/FamilyDetails.tsx
> +              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco l
Etant donné que je ne recevais pas les infos, c'est un texte "temporaire" pour voir à quoi ressemble le tout.

2024-08-03 20:54 UTC, arnaudpant requested changes

2024-08-03 20:54 UTC, arnaudpant commented on src/components/hostFamilyCard/HostFamilyCard.tsx
> +                onClick={() => navigate("/not-sale")}
Normalement Aurelia a supprimer /not-sale puisque le bouton affiche soit 
- Plus d'infos et => la page de la famille
- Soit Reserver (page de la famille) et => fake stripe

2024-08-05 18:47 UTC, arnaudpant requested changes
J'ai pull ta branche pour test:
- Bravo pour le design c'est propre, mais ....
- Pas responsive. Il faudrait que la barre de droite passe en-dessous en mobile
- Les étoiles de notes devraient etre a 4/5 par défaut, donc 4 en jaune ou pleines
- Pour les autres familles d'accueil il faudrait filtrer les autres familles dans la meme region que celle affichée et si il n'y en a pas mettre un message ou autre.

2024-08-06 09:56 UTC, Caro-L-dev commented
> J'ai pull ta branche pour test:
> 
> * Bravo pour le design c'est propre, mais ....
> * Pas responsive. Il faudrait que la barre de droite passe en-dessous en mobile
> * Les étoiles de notes devraient etre a 4/5 par défaut, donc 4 en jaune ou pleines
> * Pour les autres familles d'accueil il faudrait filtrer les autres familles dans la meme region que celle affichée et si il n'y en a pas mettre un message ou autre.

Il n'y a qu'une seule famille dispo par région, il faudrait en voir plusieurs pour voir ce que cela donne dans les suggestions de familles affichées en bas.

2024-08-06 19:43 UTC, arnaudpant requested changes

2024-08-06 19:43 UTC, arnaudpant commented on src/pages/family/score/Score.tsx
> +      <span className="flex items-center">
Pour avoir quelque chose d'aleatoire, tu peux utiliser un composant ` <UserNoteStars note={()=>getRandomIndex(1, 5)} />`
avec
```
export default function getRandomIndex(min: number, max: number): number {
    min = Math.ceil(min)
    max = Math.ceil(max)
    return Math.floor(Math.random() * (max - min + 1) + min)
}
```
et
```
const UserNoteStars: React.FC<{ note: number }> = ({ note }) => {
  const NOTE_MAX = 5;
  const NOTE_MIN = 1;
  if (note > NOTE_MAX || note < NOTE_MIN) return null;
  return (
    <div className="flex">
      {Array.from({ length: note }, (_, index) => {
        return <Star color="orange" fill="orange" key={index} />;
      })}
    </div>
  );
};

export default UserNoteStars;
```

2024-08-06 19:43 UTC, arnaudpant commented on src/pages/family/sidebar/Sidebar.tsx
> +    <div className="w-full md:w-2/6 bg-neutral-100 text-center p-2 md:p-7 text-xl">
Toujours un comportement bizarre quand on change la taille d'ecran !
Le composant sort dépasse de sa div parent en plus.
Les 2 boutons gangneraient a etre en colonne
Pas assez de marge/gap entre les elements

2024-08-06 19:43 UTC, arnaudpant commented on src/pages/family/FamilyDetails.tsx
> +    <div className="flex flex-col md:flex-row justify-between">
passe plus tot en flex-row

2024-08-06 19:43 UTC, arnaudpant commented on src/pages/family/details/Details.tsx
> +        <OtherFamilies />
Ici je passerai en props `state.region` dans  `<OtherFamilies />`
Dans `<OtherFamilies familyRegion={state.region} />` je récupère et filtre les familles qui ont la meme region que la props familyRegion pour les afficher

2024-08-06 19:43 UTC, arnaudpant commented on src/pages/family/details/Details.tsx
> +        <Opinion />
C'est bien de découper (je le fais pas assez) mais j'aurais plutot découpé comme ceci:
```
const FamilyDetails = () => {
  return (
    <div className="flex flex-col md:flex-row justify-between">
      <Details />
      <Sidebar />
      <Opinion />
      <OtherFamilies />
    </div>
``` 
En laissant Opinion et OtherFamilies dans Details tu vas les re-render a chaque re-render de Details et FamilyDetails puisque ce sont des children alors qu'en les laissant dans FamilyDetails tu ne les re-render que lorsque FamilyDetails est re-render
De plus tu peux mettre le ` const { state } = useAuthNavigation();` dans FamilyDetails et passer en props ce que les composants enfants ont vraiment besoin.
Effets kissCool en passant que des props dans les composants c'est bcp plus facile de faire leurs tests unitaires

2024-08-09 20:14 UTC, arnaudpant commented on src/pages/family/details/Details.tsx
> +        <Opinion />
Modifié

2024-08-09 20:55 UTC, arnaudpant commented on src/pages/family/score/Score.tsx
> +      <span className="flex items-center">
Fait

2024-08-10 18:10 UTC, Caro-L-dev commented on src/components/common/UserNoteStars.tsx
1 - Le fichier UserNoteStars doit se trouver à l'intérieur d'un dossier du même nom pour rester cohérent au niveau de l'architecture du dossier.
2 - Il manque les étoiles vides si par exemple le score n'est pas égal à 5 étoiles pleines.

2024-08-10 18:14 UTC, Caro-L-dev commented on src/pages/family/otherFamilies/OtherFamilies.tsx
Family or families* not familly!

2024-08-10 18:15 UTC, Caro-L-dev commented on src/pages/family/score/Score.tsx
Si le composant Score ne sert plus, il faut le supprimer.

2024-08-10 19:32 UTC, arnaudpant commented on src/components/common/UserNoteStars.tsx
Fait pour le fichier
Pour les etoiles egalement

2024-08-10 19:34 UTC, arnaudpant commented on src/pages/family/otherFamilies/OtherFamilies.tsx
fait

2024-08-10 19:34 UTC, arnaudpant commented on src/pages/family/score/Score.tsx
Fait

2024-08-10 19:36 UTC, arnaudpant commented
Corrections faites.
Pour les familles il n'y a que 2 regions qui ont plus d'une famille (bretagne et une autre) mais c'est a Aurelie d'en ajouter

2024-08-13 18:33 UTC, arnaudpant approved these changes

2024-08-13 18:34 UTC, merged