feature:Manage student registration and information page
Caro-L-dev/lingi-club pull request #64
Opened 2024-08-13 11:02 UTC by Aurelia77

2024-08-13 18:32 UTC, arnaudpant requested changes

2024-08-13 18:32 UTC, arnaudpant commented on src/pages/registration/RegistrationDetails.tsx
> +    console.log("data", data); ///////////////////////////////////////////////////////////////////////////
console.log ...

2024-08-13 18:32 UTC, arnaudpant commented on src/pages/registration/RegistrationDetails.tsx
>        }
Mettre un toast.error("Un probleme est survenu"

2024-08-13 18:32 UTC, arnaudpant commented on src/pages/user-infos/UserInfosForm.tsx
> +                            // HTML form field values are always strings: we convert them to numbers
com a supprimer

2024-08-14 10:24 UTC, Aurelia77 commented on src/pages/registration/RegistrationDetails.tsx
>        }
Fait !

2024-08-14 10:24 UTC, Aurelia77 commented on src/pages/registration/RegistrationDetails.tsx
> +    console.log("data", data); ///////////////////////////////////////////////////////////////////////////
oui j'avais mis des //////////// pour y penser mais j'ai encore oublié :( :)

2024-08-14 10:34 UTC, Aurelia77 commented on src/pages/user-infos/UserInfosForm.tsx
> +                            // HTML form field values are always strings: we convert them to numbers
ok

2024-08-14 19:03 UTC, arnaudpant approved these changes

2024-08-14 19:04 UTC, merged