Feature/authentification
Caro-L-dev/lingi-club pull request #7
Opened 2024-05-24 15:50 UTC by Aurelia77

- package => Installation des dépendances firebase (pnpm intall firebase)
- firebase/firebase-config. => Initialisation de firebase et son authentification
- api/authentification => création des hook useRegister et useLogIn afin de les utiliser dans les pages d'Inscription et connexion

2024-05-25 11:52 UTC, arnaudpant requested changes
Quelques changements a apporter.

METTRE LE DOSSIER API DANS SRC SINON IL NE TROUVE PAS LES IMPORTS

C'est .env.local et non .env-local

Attention de ne pas merge ensuite, il faudra une autre revue de code

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +export const useRegister = () => {
C'est un hook donc nommer ton fichier useQuelqueChose.ts et le mettre dans un dossier hooks. EQt comme il ne renvoi pas de JSX c'est un fichier .ts

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +  const register = (email : string, password : string) => {
Créer un type générique à part, voir dans un fichier séparé:
type RegisterType = {
email: string;
password: string;
}
Et comme tu déclares un type et pas un objet c'est ; et non pas , entre chaque props

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +export const useLogIn = () => {
Soit faire un hook qui return les functions { register, login, loading et error }, soit séparer en 2 fichiers .ts dans un dossier hooks

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +        console.log("New User =>", userCredential.user)
Pas de console.log inutile
Mais un toast.success serait pas mal avec la librairie toastify par exemple

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +        console.log("Error =>", error.message
préférer un console.error et encore mieux utiliser un toast.error

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +        console.log("LoggedIn User =>", userCredential.user)
Idem console.log inutile

2024-05-25 11:52 UTC, arnaudpant commented on api/authentification.ts
> +  return { logIn, loading, error };
QUESTION: logIn te return quoi comme data ? email et password ?

2024-05-25 16:16 UTC, arnaudpant commented
Tu peux envisager de créer un context et de mettre les infos du user dedans car on va avoir besoin d'interroger souvent firebase pour savoir si le user est connecté, ce qui va entrainer de nombreux appel a l'API de Firebase. En mettant cette info dans un context, on interroge le context et pas l'API sauf si le user n'est pas connecté

2024-05-25 21:20 UTC, arnaudpant commented
PB avec ce que return ton hook. logIn ne return pas ce qu'il nous faut, il log une function ...

 J'ai modifié comme ceci pour te donner une piste, nous a notre niveau on veut juste savoir si le user est connecté avec ses identifiants
<img width="562" alt="Capture d’écran 2024-05-25 à 23 19 55" src="https://github.com/Caro-L-dev/lingi-club/assets/54354502/1e80482d-e6e8-4757-b0cf-ec012ea6cacc">

2024-05-27 13:33 UTC, Aurelia77 commented on api/authentification.ts
> +export const useLogIn = () => {
Ok, oui c'est vrai car l'une et l'autre ne seront jamais appelées en même temps.

2024-05-27 15:41 UTC, Aurelia77 commented on api/authentification.ts
> +  return { logIn, loading, error };
J'ai modifié, maintenant ça retourne soit data (les données du user) soir une erreur.

2024-05-27 15:41 UTC, Aurelia77 commented on api/authentification.ts
> +        console.log("Error =>", error.message
Ok pour le Toast.

2024-05-27 15:44 UTC, Aurelia77 commented
J'ai modifié comme demandé, voir pour le .env-local et je créerai un contexte par la suite.
Users de test : a@a.fr 123123 puis idem pour b@b.fr et c@c.fr.

2024-05-27 15:44 UTC, closed without merging